name: wildsense_ai
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  card_swiper: ^3.0.1
  svg_flutter: ^0.0.1
  flutter_otp_text_field: ^1.1.1
  pin_code_fields: ^8.0.1
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-HeavyItalic.otf
          weight: 800
          style: italic